name: Repository dispatch resolver

on: 
  repository_dispatch:
    types: [lse-update]

jobs:
    dispatch:
      runs-on: ubuntu-latest

      steps:
      - name: "Schedule develop build"
        run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
