name: LSE pipeline

on: [push, fork]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Determine branch name
      run: | 
        echo ${GITHUB_REF#refs/heads/}"
        "branch_name=${GITHUB_REF#refs/heads/}" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Create info file
      run: |
        echo "Author name: ${{ github.event.head_commit.author.name }}" >> commit_info.txt
        echo "Author email: ${{ github.event.head_commit.author.email }}" >> commit_info.txt
        echo "Commit hash: ${{ github.event.head_commit.id }}" >> commit_info.txt
        echo "Commit message: ${{ github.event.head_commit.message }}" >> commit_info.txt
        echo "Active branch: $env:branch_name" >> commit_info.txt

    - name: Preconfigure
      id: preconfigure
      run: |
          if ($env:branch_name -eq "develop") {
            $type="nightly"
          }
          elseif ($env:branch_name -like "release/*") {
            $type="release"
          }
          elseif ($env:branch_name -like "feature/*") {
            $type="feature"
          }
          else {
            $type="experimental"
          }
          "build_type=$type" | Out-File -FilePath $env:GITHUB_ENV  -Append

    - name: Print
      run: echo "$env:build_type - $env:branch_name"

