name: LSE pipeline

on: [push, fork]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set
      run: | 
        "build_type=experimental" | Out-File -FilePath $env:GITHUB_ENV  -Append

    - name: Print 1
      run: echo $env:build_type

    - name: Print 2
      run: echo $Env:build_type

    - name: Print 3
      run: echo "$env:build_type"

    - name: Print 3
      run: echo "$Env:build_type"

