name: LSE pipeline

on: [push, fork]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create info file
      run: |
        echo "Author name: ${{ github.event.head_commit.author.name }}" >> commit_info.txt
        echo "Author email: ${{ github.event.head_commit.author.email }}" >> commit_info.txt
        echo "Commit hash: ${{ github.event.head_commit.id }}" >> commit_info.txt
        echo "Commit message: ${{ github.event.head_commit.message }}" >> commit_info.txt
    - name: Archive info file
      uses: actions/upload-artifact@v2
      with:
        name: commit_info
        path: commit_info.txt

    - name: Directory
      run: mkdir -p ${{github.workspace}}/directory

    - name: Directory ls
      run: ls && ls ${{github.workspace}} && ls ${{github.workspace}}/directory

    - name: File 1 
      run: |
        echo "Author name: ${{ github.event.head_commit.author.name }}" >> ${{github.workspace}}/directory/file1.txt

    - name: File 2
      run: |
        echo "Author name: ${{ github.event.head_commit.author.name }}" >> ${{github.workspace}}/directory/file2.txt

    - name: Archive Release build
      uses: actions/upload-artifact@v4
      with:
        name: LiveSyncEngine
        path: ${{github.workspace}}/directory
