name: LSE pipeline

on: [push, fork]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set color
        id: color-selector
        run: |
          echo "SELECTED_COLOR=green" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      - name: Get color
        run: echo "The selected color is ${{ steps.color-selector.outputs.SELECTED_COLOR }}"

