name: LSE pipeline

on: [push, fork]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set color
        id: color-selector
        run: |
          echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
          echo $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
      - name: Get color
        run: echo "The selected color is ${{ steps.color-selector.outputs.SELECTED_COLOR }}"

